version: '3.7'

volumes:
  alquran_cdn:

services:
  #######################################
  # App Container
  #######################################
  cdn:
    image: ghcr.io/islamic-network/cdn.alquran.cloud:latest
    volumes:
      - alquran_cdn:/var/www/storage
    deploy:
      replicas: 2
      update_config:
        delay: 10s
      placement:
        constraints:
          - node.role != manager
          - node.labels.type == worker-app
      resources:
        limits:
          memory: 250M
        reservations:
          memory: 32M
